finalize: push differently
* don't push 'prepare for next release' changes to release/A.B.C
* push in workflow instead of script

diff --git a/scripts/release/finalize b/scripts/release/finalize
--- a/scripts/release/finalize
+++ b/scripts/release/finalize
@@ -1,13 +1,10 @@
 #!/usr/bin/env bash
 
 # run by the release-finalize.yml github action workflow
-# * start from a release/A.B.C branch
-# * revert notification channel and remove generated static files
+# * merge release/A.B.C branch into release/A.B.x
+# * remove generated static files
 # * update version in version.go and scripts/release/previous.version
-# * commit and merge changes into the source release/A.B.x branch
-
-# by default, it will do everything except for `git push`
-# unless you `export DO_PUSH=true`
+# * commit and merge changes into release/A.B.x
 
 [ -n "$DEBUG" ] && set -x
 set -euo pipefail
@@ -16,25 +13,31 @@ source "$(dirname "${BASH_SOURCE[0]}")/check-working-dir"
 
 echo 'Checking variables'
   MERGE_FROM="${MERGE_FROM:-$(git branch --show-current)}"
-  DO_PUSH="${DO_PUSH:-false}"
   # vars displayed this way for easier troubleshooting
   cat <<VARS
 export NEW_VERSION='${NEW_VERSION?is required}'
 export MERGE_INTO='${MERGE_INTO?is required}'
 export MERGE_FROM='$MERGE_FROM'
-export DO_PUSH='$DO_PUSH'
 $0
 
 VARS
 
 echo 'Ensuring branches'
-  # merge-from second, so we proceed from there.
-  for b in "$MERGE_INTO" "$MERGE_FROM"; do
+  # merge-into second, so we proceed from there.
+  for b in "$MERGE_FROM" "$MERGE_INTO"; do
     git fetch origin "$b"
     git switch "$b"
     git pull origin "$b"
   done
 echo
+
+echo "Merging changes from '$MERGE_FROM' into '$MERGE_INTO'"
+  if ! git merge --no-edit "$MERGE_FROM"; then
+    echo "::error::failed to merge $MERGE_FROM into $MERGE_INTO"
+    git status
+    git diff --color=always | /bin/cat
+    exit 1
+  fi
 
 echo 'Updating magic strings in magic files'
   if [ -n "$(semver get prerel "$NEW_VERSION")" ]; then
@@ -63,14 +66,6 @@ echo 'Removing generated static assets'
   find . -name '*.generated.go' -exec git rm -f '{}' \;
 echo
 
-push() {
-  if [ "$DO_PUSH" == 'true' ]; then
-    git push origin "$1"
-  else
-    echo "::warning::DO_PUSH != true, so skipping 'git push origin $1'"
-  fi
-}
-
 echo 'Committing changes'
   # Display staged and unstaged diffs, skipping deleted files to avoid
   # cluttering the output with the generated files.
@@ -82,16 +77,5 @@ echo 'Committing changes'
     echo '::notice::No files were updated'
   else
     git commit --message "release: Prepare for next release post-$NEW_VERSION"
-    push "$MERGE_FROM"
   fi
 echo
-
-echo "Merging changes from '$MERGE_FROM' into '$MERGE_INTO'"
-  git switch "$MERGE_INTO"
-  if ! git merge --no-edit "$MERGE_FROM"; then
-    echo "::error::failed to merge $MERGE_FROM into $MERGE_INTO"
-    git status
-    git diff --color=always | /bin/cat
-    exit 1
-  fi
-  push "$MERGE_INTO"
