release: changes to prepare/changelog/finalize
big ticket items:
* stop changing the slack channel; just use what's in .release/ci.hcl
* put "LAST_RELEASE" value in scripts/release/previous.version instead
  * a follow-up will remove it from GNUmakefile, to avoid merge conflicts here
* enable finalize script to push (squashed) changes to main branch

minutia:
* main-branch input allows for testing "finalize" to non-main branch
* move `git commit` and `git push` out of prepare/changelog scripts
  * the workflow does this at the end instead,
    to make a single commit with generated files and changelog
  * ALLOW_DIRTY_WORKTREE env skips that check,
    while still protecting human users from messing up their local git
* ditto `git push` in finalize script
* new branch prefix is detected dynamically based on source branch
  * still only needed for testing, to use non-"release/" prefix
* tighten some 'Checking variables' output

diff --git a/scripts/release/finalize b/scripts/release/finalize
--- a/scripts/release/finalize
+++ b/scripts/release/finalize
@@ -1,13 +1,10 @@
 #!/usr/bin/env bash
 
 # run by the release-finalize.yml github action workflow
-# * start from a release/A.B.C branch
-# * revert notification channel and remove generated static files
-# * update version in version.go and LAST_RELEASE in GNUMakefile
-# * commit and merge changes into the source release/A.B.x branch
-
-# by default, it will do everything except for `git push`
-# unless you `export DO_PUSH=true`
+# * merge release/A.B.C branch into release/A.B.x
+# * remove generated static files
+# * update version in version.go and scripts/release/previous.version
+# * commit and merge changes into release/A.B.x
 
 [ -n "$DEBUG" ] && set -x
 set -euo pipefail
@@ -16,36 +13,46 @@ source "$(dirname "${BASH_SOURCE[0]}")/check-working-dir"
 
 echo 'Checking variables'
   MERGE_FROM="${MERGE_FROM:-$(git branch --show-current)}"
-  DO_PUSH="${DO_PUSH:-false}"
   # vars displayed this way for easier troubleshooting
   cat <<VARS
-\`\`\`
-# required:
 export NEW_VERSION='${NEW_VERSION?is required}'
 export MERGE_INTO='${MERGE_INTO?is required}'
-# derived:
 export MERGE_FROM='$MERGE_FROM'
-# other:
-export DO_PUSH='$DO_PUSH'
-
 $0
-\`\`\`
 
 VARS
 
 echo 'Ensuring branches'
-  # merge-from second, so we proceed from there.
-  for b in "$MERGE_INTO" "$MERGE_FROM"; do
+  # merge-into second, so we proceed from there.
+  for b in "$MERGE_FROM" "$MERGE_INTO"; do
     git fetch origin "$b"
     git switch "$b"
     git pull origin "$b"
   done
 echo
 
-echo 'Updating magic strings in magic files'
-  # restore original notification_channel
-  git restore --source="origin/$MERGE_INTO" -- .release/ci.hcl
+# if the target is main, we cherry-pick from the source and call it a day.
+if [ "$MERGE_INTO" == "${MAIN_BRANCH:-main}" ]; then
+  echo 'Target branch is main; squash-merging release commits'
 
+  # squash to exclude the generated files from git history entirely;
+  # they're big, and kept for posterity in other branches.
+  git log --grep "release:.* ${NEW_VERSION}$" --reverse --pretty='%H' \
+    "$MERGE_FROM" | xargs git cherry-pick --no-commit
+  git commit -m "release: $NEW_VERSION"
+
+  exit # nothing else to do
+fi
+
+echo "Merging changes from '$MERGE_FROM' into '$MERGE_INTO'"
+  if ! git merge --no-edit "$MERGE_FROM"; then
+    echo "::error::failed to merge $MERGE_FROM into $MERGE_INTO"
+    git status
+    git diff --color=always | /bin/cat
+    exit 1
+  fi
+
+echo 'Updating magic strings in magic files'
   if [ -n "$(semver get prerel "$NEW_VERSION")" ]; then
     echo "$NEW_VERSION is a prerelease; reverting changelog"
     # we'll re-update changelog for GA.
@@ -55,7 +62,9 @@ echo 'Updating magic strings in magic files'
     echo "$NEW_VERSION is not a prerelease; bumping versions"
     next_patch="$(semver bump patch "$NEW_VERSION")"
     sed -i.bak -e "s|\(Version * = *\"\)[^\"]*|\1${next_patch}|g" version/version.go
-    sed -i.bak -re "s|^(LAST_RELEASE\s+\?=\s).*$|\1$NEW_VERSION|g" GNUmakefile
+    # previous version to use next time the changelog is generated
+    prev_v='scripts/release/previous.version'
+    echo -e "$(grep '^#' "$prev_v")\n$NEW_VERSION" > "$prev_v"
   fi
 
   # set VersionPrerelease back to "dev"
@@ -70,14 +79,6 @@ echo 'Removing generated static assets'
   find . -name '*.generated.go' -exec git rm -f '{}' \;
 echo
 
-push() {
-  if [ "$DO_PUSH" == 'true' ]; then
-    git push origin "$1"
-  else
-    echo "::warning::DO_PUSH != true, so skipping 'git push origin $1'"
-  fi
-}
-
 echo 'Committing changes'
   # Display staged and unstaged diffs, skipping deleted files to avoid
   # cluttering the output with the generated files.
@@ -88,18 +89,6 @@ echo 'Committing changes'
   if git diff-index --quiet HEAD --; then
     echo '::notice::No files were updated'
   else
-    git commit --message "release: Prepare for next release post-$NEW_VERSION"
-    push "$MERGE_FROM"
+    git commit --message "release: Prepare for next release after $NEW_VERSION"
   fi
 echo
-
-echo "Merging changes from '$MERGE_FROM' into '$MERGE_INTO'"
-  git switch "$MERGE_INTO"
-  if ! git merge --no-edit "$MERGE_FROM"; then
-    echo "::error::failed to merge $MERGE_FROM into $MERGE_INTO"
-    git status
-    git diff --color=always | /bin/cat
-    exit 1
-  fi
-  push "$MERGE_INTO"
-
