disable docker image release for beta
The release pipeline for shipping docker images is failing for
1.6.0-beta.1. Remove this part of the pipeline for the beta. The image should
ship with 1.6.0-rc1 or the GA

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -281,37 +281,41 @@ jobs:
           name: ${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
           path: ${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
 
-  build-docker:
-    name: Docker ${{ matrix.arch }} build
-    needs:
-      - get-product-version
-      - build-linux
-    runs-on: [ custom, linux, xxl, 20.04 ]
-    strategy:
-      matrix:
-        arch: ["arm64", "amd64"]
-    env:
-      version: ${{needs.get-product-version.outputs.product-version}}
-    steps:
-      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
-      - name: Docker Build (Action)
-        uses: hashicorp/actions-docker-build@v1
-        with:
-          smoke_test: |
-            TEST_VERSION="$(docker run "${IMAGE_NAME}" version | awk '/Nomad v/{print $2}')"
-            if [ "${TEST_VERSION}" != "v${version}" ]; then
-              echo "Test FAILED"
-              exit 1
-            fi
-            echo "Test PASSED"
-          version: ${{env.version}}
-          target: release
-          arch: ${{matrix.arch}}
-          tags: |
-            docker.io/hashicorp/${{env.PKG_NAME}}:${{env.version}}
-          dev_tags: |
-            docker.io/hashicorppreview/${{ env.PKG_NAME }}:${{ env.version }}-dev
-            docker.io/hashicorppreview/${{ env.PKG_NAME }}:${{ env.version }}-${{ github.sha }}
+# TODO(tgross): docker image release commented-out for 1.6.0-beta.1 so that we
+# can ship the beta while debugging the release pipeline. The image should ship
+# with 1.6.0-rc1 or the GA
+#
+  # build-docker:
+  #   name: Docker ${{ matrix.arch }} build
+  #   needs:
+  #     - get-product-version
+  #     - build-linux
+  #   runs-on: [ custom, linux, xxl, 20.04 ]
+  #   strategy:
+  #     matrix:
+  #       arch: ["arm64", "amd64"]
+  #   env:
+  #     version: ${{needs.get-product-version.outputs.product-version}}
+  #   steps:
+  #     - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+  #     - name: Docker Build (Action)
+  #       uses: hashicorp/actions-docker-build@v1
+  #       with:
+  #         smoke_test: |
+  #           TEST_VERSION="$(docker run "${IMAGE_NAME}" version | awk '/Nomad v/{print $2}')"
+  #           if [ "${TEST_VERSION}" != "v${version}" ]; then
+  #             echo "Test FAILED"
+  #             exit 1
+  #           fi
+  #           echo "Test PASSED"
+  #         version: ${{env.version}}
+  #         target: release
+  #         arch: ${{matrix.arch}}
+  #         tags: |
+  #           docker.io/hashicorp/${{env.PKG_NAME}}:${{env.version}}
+  #         dev_tags: |
+  #           docker.io/hashicorppreview/${{ env.PKG_NAME }}:${{ env.version }}-dev
+  #           docker.io/hashicorppreview/${{ env.PKG_NAME }}:${{ env.version }}-${{ github.sha }}
 
 permissions:
   contents: read
