continue-on-error back in, but explicit success check after exam

diff --git a/.github/workflows/test-ui.yml b/.github/workflows/test-ui.yml
--- a/.github/workflows/test-ui.yml
+++ b/.github/workflows/test-ui.yml
@@ -36,6 +36,7 @@ jobs:
       - pre-test
     runs-on: ${{ endsWith(github.repository, '-enterprise') && fromJSON('["self-hosted", "ondemand", "linux", "type=m7a.2xlarge;m6a.2xlarge"]') || 'ubuntu-latest' }}
     timeout-minutes: 30
+    continue-on-error: true
     defaults:
       run:
         working-directory: ui
@@ -61,15 +62,23 @@ jobs:
           secrets: |-
             kv/data/teams/nomad/ui PERCY_TOKEN ;
       - name: ember exam
+        id: exam
         env:
           PERCY_TOKEN: ${{ env.PERCY_TOKEN || secrets.PERCY_TOKEN }}
           PERCY_PARALLEL_NONCE: ${{ needs.pre-test.outputs.nonce }}
         run: |
           yarn exam:parallel --split=${{ matrix.split }} --partition=${{ matrix.partition }} --json-report=test-results/test-results.json
-        # continue-on-error: true
+      # We have continue-on-error set to true, but we still want to alert the author if
+      # there are test failures or timeouts. Without it, we'll get errors in our output,
+      # but the workflow will still succeed / have a green checkmark.
       - name: Express timeout failure
         if: ${{ failure() }}
         run: exit 1
+      - name: Check test status
+        if: steps.exam.outcome != 'success'
+        run: |
+          echo "Tests failed or timed out in partition ${{ matrix.partition }}"
+          exit 1
       - name: Upload partition test results
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
