continue-on-error set to false to get things red when appropriate

diff --git a/.github/workflows/test-ui.yml b/.github/workflows/test-ui.yml
--- a/.github/workflows/test-ui.yml
+++ b/.github/workflows/test-ui.yml
@@ -66,10 +66,10 @@ jobs:
           PERCY_PARALLEL_NONCE: ${{ needs.pre-test.outputs.nonce }}
         run: |
           yarn exam:parallel --split=${{ matrix.split }} --partition=${{ matrix.partition }} --json-report=test-results/test-results.json
-        continue-on-error: true
-      - name: Express timeout failure
-        if: ${{ failure() }}
-        run: exit 1
+        continue-on-error: false
+      # - name: Express timeout failure
+      #   if: ${{ failure() }}
+      #   run: exit 1
       - name: Upload partition test results
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
